//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 2015/06/17 3:33:41
namespace HiyoshiCfhClient.HiyoshiCfhWeb.Models
{
    /// <summary>
    /// There are no comments for ShipTypeSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("ShipTypeSingle")]
    public partial class ShipTypeSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<ShipType>
    {
        /// <summary>
        /// Initialize a new ShipTypeSingle object.
        /// </summary>
        public ShipTypeSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new ShipTypeSingle object.
        /// </summary>
        public ShipTypeSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new ShipTypeSingle object.
        /// </summary>
        public ShipTypeSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<ShipType> query)
            : base(query) {}

    }
    /// <summary>
    /// There are no comments for ShipType in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ShipTypeId
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("ShipTypeId")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("ShipType")]
    public partial class ShipType : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new ShipType object.
        /// </summary>
        /// <param name="shipTypeId">Initial value of ShipTypeId.</param>
        /// <param name="sortNumber">Initial value of SortNumber.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
        public static ShipType CreateShipType(int shipTypeId, int sortNumber)
        {
            ShipType shipType = new ShipType();
            shipType.ShipTypeId = shipTypeId;
            shipType.SortNumber = sortNumber;
            return shipType;
        }
        /// <summary>
        /// There are no comments for Property ShipTypeId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ShipTypeId")]
        public int ShipTypeId
        {
            get
            {
                return this._ShipTypeId;
            }
            set
            {
                this.OnShipTypeIdChanging(value);
                this._ShipTypeId = value;
                this.OnShipTypeIdChanged();
                this.OnPropertyChanged("ShipTypeId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
        private int _ShipTypeId;
        partial void OnShipTypeIdChanging(int value);
        partial void OnShipTypeIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Name")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property SortNumber in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("SortNumber")]
        public int SortNumber
        {
            get
            {
                return this._SortNumber;
            }
            set
            {
                this.OnSortNumberChanging(value);
                this._SortNumber = value;
                this.OnSortNumberChanged();
                this.OnPropertyChanged("SortNumber");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
        private int _SortNumber;
        partial void OnSortNumberChanging(int value);
        partial void OnSortNumberChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for ShipInfoSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("ShipInfoSingle")]
    public partial class ShipInfoSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<ShipInfo>
    {
        /// <summary>
        /// Initialize a new ShipInfoSingle object.
        /// </summary>
        public ShipInfoSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new ShipInfoSingle object.
        /// </summary>
        public ShipInfoSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new ShipInfoSingle object.
        /// </summary>
        public ShipInfoSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<ShipInfo> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for ShipType in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ShipType")]
        public global::HiyoshiCfhClient.HiyoshiCfhWeb.Models.ShipTypeSingle ShipType
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._ShipType == null))
                {
                    this._ShipType = new global::HiyoshiCfhClient.HiyoshiCfhWeb.Models.ShipTypeSingle(this.Context, GetPath("ShipType"));
                }
                return this._ShipType;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
        private global::HiyoshiCfhClient.HiyoshiCfhWeb.Models.ShipTypeSingle _ShipType;
    }
    /// <summary>
    /// There are no comments for ShipInfo in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ShipInfoId
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("ShipInfoId")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("ShipInfo")]
    public partial class ShipInfo : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new ShipInfo object.
        /// </summary>
        /// <param name="shipInfoId">Initial value of ShipInfoId.</param>
        /// <param name="sortId">Initial value of SortId.</param>
        /// <param name="shipSpeed">Initial value of ShipSpeed.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
        public static ShipInfo CreateShipInfo(int shipInfoId, int sortId, global::HiyoshiCfhClient.HiyoshiCfhWeb.Models.ShipSpeed shipSpeed)
        {
            ShipInfo shipInfo = new ShipInfo();
            shipInfo.ShipInfoId = shipInfoId;
            shipInfo.SortId = sortId;
            shipInfo.ShipSpeed = shipSpeed;
            return shipInfo;
        }
        /// <summary>
        /// There are no comments for Property ShipInfoId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ShipInfoId")]
        public int ShipInfoId
        {
            get
            {
                return this._ShipInfoId;
            }
            set
            {
                this.OnShipInfoIdChanging(value);
                this._ShipInfoId = value;
                this.OnShipInfoIdChanged();
                this.OnPropertyChanged("ShipInfoId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
        private int _ShipInfoId;
        partial void OnShipInfoIdChanging(int value);
        partial void OnShipInfoIdChanged();
        /// <summary>
        /// There are no comments for Property SortId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("SortId")]
        public int SortId
        {
            get
            {
                return this._SortId;
            }
            set
            {
                this.OnSortIdChanging(value);
                this._SortId = value;
                this.OnSortIdChanged();
                this.OnPropertyChanged("SortId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
        private int _SortId;
        partial void OnSortIdChanging(int value);
        partial void OnSortIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Name")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property ShipTypeId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ShipTypeId")]
        public global::System.Nullable<int> ShipTypeId
        {
            get
            {
                return this._ShipTypeId;
            }
            set
            {
                this.OnShipTypeIdChanging(value);
                this._ShipTypeId = value;
                this.OnShipTypeIdChanged();
                this.OnPropertyChanged("ShipTypeId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
        private global::System.Nullable<int> _ShipTypeId;
        partial void OnShipTypeIdChanging(global::System.Nullable<int> value);
        partial void OnShipTypeIdChanged();
        /// <summary>
        /// There are no comments for Property ShipSpeed in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ShipSpeed")]
        public global::HiyoshiCfhClient.HiyoshiCfhWeb.Models.ShipSpeed ShipSpeed
        {
            get
            {
                return this._ShipSpeed;
            }
            set
            {
                this.OnShipSpeedChanging(value);
                this._ShipSpeed = value;
                this.OnShipSpeedChanged();
                this.OnPropertyChanged("ShipSpeed");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
        private global::HiyoshiCfhClient.HiyoshiCfhWeb.Models.ShipSpeed _ShipSpeed;
        partial void OnShipSpeedChanging(global::HiyoshiCfhClient.HiyoshiCfhWeb.Models.ShipSpeed value);
        partial void OnShipSpeedChanged();
        /// <summary>
        /// There are no comments for Property NextRemodelingLevel in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("NextRemodelingLevel")]
        public global::System.Nullable<int> NextRemodelingLevel
        {
            get
            {
                return this._NextRemodelingLevel;
            }
            set
            {
                this.OnNextRemodelingLevelChanging(value);
                this._NextRemodelingLevel = value;
                this.OnNextRemodelingLevelChanged();
                this.OnPropertyChanged("NextRemodelingLevel");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
        private global::System.Nullable<int> _NextRemodelingLevel;
        partial void OnNextRemodelingLevelChanging(global::System.Nullable<int> value);
        partial void OnNextRemodelingLevelChanged();
        /// <summary>
        /// There are no comments for Property ShipType in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ShipType")]
        public global::HiyoshiCfhClient.HiyoshiCfhWeb.Models.ShipType ShipType
        {
            get
            {
                return this._ShipType;
            }
            set
            {
                this.OnShipTypeChanging(value);
                this._ShipType = value;
                this.OnShipTypeChanged();
                this.OnPropertyChanged("ShipType");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
        private global::HiyoshiCfhClient.HiyoshiCfhWeb.Models.ShipType _ShipType;
        partial void OnShipTypeChanging(global::HiyoshiCfhClient.HiyoshiCfhWeb.Models.ShipType value);
        partial void OnShipTypeChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for AdmiralSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("AdmiralSingle")]
    public partial class AdmiralSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Admiral>
    {
        /// <summary>
        /// Initialize a new AdmiralSingle object.
        /// </summary>
        public AdmiralSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new AdmiralSingle object.
        /// </summary>
        public AdmiralSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new AdmiralSingle object.
        /// </summary>
        public AdmiralSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<Admiral> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for Ships in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Ships")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::HiyoshiCfhClient.HiyoshiCfhWeb.Models.Ship> Ships
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Ships == null))
                {
                    this._Ships = Context.CreateQuery<global::HiyoshiCfhClient.HiyoshiCfhWeb.Models.Ship>(GetPath("Ships"));
                }
                return this._Ships;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::HiyoshiCfhClient.HiyoshiCfhWeb.Models.Ship> _Ships;
    }
    /// <summary>
    /// There are no comments for Admiral in the schema.
    /// </summary>
    /// <KeyProperties>
    /// AdmiralId
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("AdmiralId")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("Admiral")]
    public partial class Admiral : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Admiral object.
        /// </summary>
        /// <param name="admiralId">Initial value of AdmiralId.</param>
        /// <param name="memberId">Initial value of MemberId.</param>
        /// <param name="experience">Initial value of Experience.</param>
        /// <param name="level">Initial value of Level.</param>
        /// <param name="maxShipCount">Initial value of MaxShipCount.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
        public static Admiral CreateAdmiral(int admiralId, int memberId, int experience, int level, int maxShipCount)
        {
            Admiral admiral = new Admiral();
            admiral.AdmiralId = admiralId;
            admiral.MemberId = memberId;
            admiral.Experience = experience;
            admiral.Level = level;
            admiral.MaxShipCount = maxShipCount;
            return admiral;
        }
        /// <summary>
        /// There are no comments for Property AdmiralId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("AdmiralId")]
        public int AdmiralId
        {
            get
            {
                return this._AdmiralId;
            }
            set
            {
                this.OnAdmiralIdChanging(value);
                this._AdmiralId = value;
                this.OnAdmiralIdChanged();
                this.OnPropertyChanged("AdmiralId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
        private int _AdmiralId;
        partial void OnAdmiralIdChanging(int value);
        partial void OnAdmiralIdChanged();
        /// <summary>
        /// There are no comments for Property MemberId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("MemberId")]
        public int MemberId
        {
            get
            {
                return this._MemberId;
            }
            set
            {
                this.OnMemberIdChanging(value);
                this._MemberId = value;
                this.OnMemberIdChanged();
                this.OnPropertyChanged("MemberId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
        private int _MemberId;
        partial void OnMemberIdChanging(int value);
        partial void OnMemberIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Name")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Experience in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Experience")]
        public int Experience
        {
            get
            {
                return this._Experience;
            }
            set
            {
                this.OnExperienceChanging(value);
                this._Experience = value;
                this.OnExperienceChanged();
                this.OnPropertyChanged("Experience");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
        private int _Experience;
        partial void OnExperienceChanging(int value);
        partial void OnExperienceChanged();
        /// <summary>
        /// There are no comments for Property Level in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Level")]
        public int Level
        {
            get
            {
                return this._Level;
            }
            set
            {
                this.OnLevelChanging(value);
                this._Level = value;
                this.OnLevelChanged();
                this.OnPropertyChanged("Level");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
        private int _Level;
        partial void OnLevelChanging(int value);
        partial void OnLevelChanged();
        /// <summary>
        /// There are no comments for Property MaxShipCount in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("MaxShipCount")]
        public int MaxShipCount
        {
            get
            {
                return this._MaxShipCount;
            }
            set
            {
                this.OnMaxShipCountChanging(value);
                this._MaxShipCount = value;
                this.OnMaxShipCountChanged();
                this.OnPropertyChanged("MaxShipCount");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
        private int _MaxShipCount;
        partial void OnMaxShipCountChanging(int value);
        partial void OnMaxShipCountChanged();
        /// <summary>
        /// There are no comments for Property Rank in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Rank")]
        public string Rank
        {
            get
            {
                return this._Rank;
            }
            set
            {
                this.OnRankChanging(value);
                this._Rank = value;
                this.OnRankChanged();
                this.OnPropertyChanged("Rank");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
        private string _Rank;
        partial void OnRankChanging(string value);
        partial void OnRankChanged();
        /// <summary>
        /// There are no comments for Property Ships in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Ships")]
        public global::Microsoft.OData.Client.DataServiceCollection<global::HiyoshiCfhClient.HiyoshiCfhWeb.Models.Ship> Ships
        {
            get
            {
                return this._Ships;
            }
            set
            {
                this.OnShipsChanging(value);
                this._Ships = value;
                this.OnShipsChanged();
                this.OnPropertyChanged("Ships");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::HiyoshiCfhClient.HiyoshiCfhWeb.Models.Ship> _Ships = new global::Microsoft.OData.Client.DataServiceCollection<global::HiyoshiCfhClient.HiyoshiCfhWeb.Models.Ship>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnShipsChanging(global::Microsoft.OData.Client.DataServiceCollection<global::HiyoshiCfhClient.HiyoshiCfhWeb.Models.Ship> value);
        partial void OnShipsChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for ShipSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("ShipSingle")]
    public partial class ShipSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Ship>
    {
        /// <summary>
        /// Initialize a new ShipSingle object.
        /// </summary>
        public ShipSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new ShipSingle object.
        /// </summary>
        public ShipSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new ShipSingle object.
        /// </summary>
        public ShipSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<Ship> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for Admiral in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Admiral")]
        public global::HiyoshiCfhClient.HiyoshiCfhWeb.Models.AdmiralSingle Admiral
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Admiral == null))
                {
                    this._Admiral = new global::HiyoshiCfhClient.HiyoshiCfhWeb.Models.AdmiralSingle(this.Context, GetPath("Admiral"));
                }
                return this._Admiral;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
        private global::HiyoshiCfhClient.HiyoshiCfhWeb.Models.AdmiralSingle _Admiral;
        /// <summary>
        /// There are no comments for ShipInfo in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ShipInfo")]
        public global::HiyoshiCfhClient.HiyoshiCfhWeb.Models.ShipInfoSingle ShipInfo
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._ShipInfo == null))
                {
                    this._ShipInfo = new global::HiyoshiCfhClient.HiyoshiCfhWeb.Models.ShipInfoSingle(this.Context, GetPath("ShipInfo"));
                }
                return this._ShipInfo;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
        private global::HiyoshiCfhClient.HiyoshiCfhWeb.Models.ShipInfoSingle _ShipInfo;
    }
    /// <summary>
    /// There are no comments for Ship in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ShipUid
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("ShipUid")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("Ship")]
    public partial class Ship : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Ship object.
        /// </summary>
        /// <param name="shipUid">Initial value of ShipUid.</param>
        /// <param name="shipId">Initial value of ShipId.</param>
        /// <param name="level">Initial value of Level.</param>
        /// <param name="isLocked">Initial value of IsLocked.</param>
        /// <param name="exp">Initial value of Exp.</param>
        /// <param name="expForNextLevel">Initial value of ExpForNextLevel.</param>
        /// <param name="hp">Initial value of Hp.</param>
        /// <param name="fuel">Initial value of Fuel.</param>
        /// <param name="bull">Initial value of Bull.</param>
        /// <param name="firepower">Initial value of Firepower.</param>
        /// <param name="torpedo">Initial value of Torpedo.</param>
        /// <param name="aA">Initial value of AA.</param>
        /// <param name="armer">Initial value of Armer.</param>
        /// <param name="luck">Initial value of Luck.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
        public static Ship CreateShip(int shipUid, 
                    int shipId, 
                    int level, 
                    bool isLocked, 
                    int exp, 
                    int expForNextLevel, 
                    int hp, 
                    int fuel, 
                    int bull, 
                    int firepower, 
                    int torpedo, 
                    int aA, 
                    int armer, 
                    int luck)
        {
            Ship ship = new Ship();
            ship.ShipUid = shipUid;
            ship.ShipId = shipId;
            ship.Level = level;
            ship.IsLocked = isLocked;
            ship.Exp = exp;
            ship.ExpForNextLevel = expForNextLevel;
            ship.Hp = hp;
            ship.Fuel = fuel;
            ship.Bull = bull;
            ship.Firepower = firepower;
            ship.Torpedo = torpedo;
            ship.AA = aA;
            ship.Armer = armer;
            ship.Luck = luck;
            return ship;
        }
        /// <summary>
        /// There are no comments for Property ShipUid in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ShipUid")]
        public int ShipUid
        {
            get
            {
                return this._ShipUid;
            }
            set
            {
                this.OnShipUidChanging(value);
                this._ShipUid = value;
                this.OnShipUidChanged();
                this.OnPropertyChanged("ShipUid");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
        private int _ShipUid;
        partial void OnShipUidChanging(int value);
        partial void OnShipUidChanged();
        /// <summary>
        /// There are no comments for Property AdmiralId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("AdmiralId")]
        public global::System.Nullable<int> AdmiralId
        {
            get
            {
                return this._AdmiralId;
            }
            set
            {
                this.OnAdmiralIdChanging(value);
                this._AdmiralId = value;
                this.OnAdmiralIdChanged();
                this.OnPropertyChanged("AdmiralId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
        private global::System.Nullable<int> _AdmiralId;
        partial void OnAdmiralIdChanging(global::System.Nullable<int> value);
        partial void OnAdmiralIdChanged();
        /// <summary>
        /// There are no comments for Property ShipId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ShipId")]
        public int ShipId
        {
            get
            {
                return this._ShipId;
            }
            set
            {
                this.OnShipIdChanging(value);
                this._ShipId = value;
                this.OnShipIdChanged();
                this.OnPropertyChanged("ShipId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
        private int _ShipId;
        partial void OnShipIdChanging(int value);
        partial void OnShipIdChanged();
        /// <summary>
        /// There are no comments for Property ShipInfoId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ShipInfoId")]
        public global::System.Nullable<int> ShipInfoId
        {
            get
            {
                return this._ShipInfoId;
            }
            set
            {
                this.OnShipInfoIdChanging(value);
                this._ShipInfoId = value;
                this.OnShipInfoIdChanged();
                this.OnPropertyChanged("ShipInfoId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
        private global::System.Nullable<int> _ShipInfoId;
        partial void OnShipInfoIdChanging(global::System.Nullable<int> value);
        partial void OnShipInfoIdChanged();
        /// <summary>
        /// There are no comments for Property Level in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Level")]
        public int Level
        {
            get
            {
                return this._Level;
            }
            set
            {
                this.OnLevelChanging(value);
                this._Level = value;
                this.OnLevelChanged();
                this.OnPropertyChanged("Level");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
        private int _Level;
        partial void OnLevelChanging(int value);
        partial void OnLevelChanged();
        /// <summary>
        /// There are no comments for Property IsLocked in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("IsLocked")]
        public bool IsLocked
        {
            get
            {
                return this._IsLocked;
            }
            set
            {
                this.OnIsLockedChanging(value);
                this._IsLocked = value;
                this.OnIsLockedChanged();
                this.OnPropertyChanged("IsLocked");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
        private bool _IsLocked;
        partial void OnIsLockedChanging(bool value);
        partial void OnIsLockedChanged();
        /// <summary>
        /// There are no comments for Property Exp in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Exp")]
        public int Exp
        {
            get
            {
                return this._Exp;
            }
            set
            {
                this.OnExpChanging(value);
                this._Exp = value;
                this.OnExpChanged();
                this.OnPropertyChanged("Exp");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
        private int _Exp;
        partial void OnExpChanging(int value);
        partial void OnExpChanged();
        /// <summary>
        /// There are no comments for Property ExpForNextLevel in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ExpForNextLevel")]
        public int ExpForNextLevel
        {
            get
            {
                return this._ExpForNextLevel;
            }
            set
            {
                this.OnExpForNextLevelChanging(value);
                this._ExpForNextLevel = value;
                this.OnExpForNextLevelChanged();
                this.OnPropertyChanged("ExpForNextLevel");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
        private int _ExpForNextLevel;
        partial void OnExpForNextLevelChanging(int value);
        partial void OnExpForNextLevelChanged();
        /// <summary>
        /// There are no comments for Property Hp in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Hp")]
        public int Hp
        {
            get
            {
                return this._Hp;
            }
            set
            {
                this.OnHpChanging(value);
                this._Hp = value;
                this.OnHpChanged();
                this.OnPropertyChanged("Hp");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
        private int _Hp;
        partial void OnHpChanging(int value);
        partial void OnHpChanged();
        /// <summary>
        /// There are no comments for Property Fuel in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Fuel")]
        public int Fuel
        {
            get
            {
                return this._Fuel;
            }
            set
            {
                this.OnFuelChanging(value);
                this._Fuel = value;
                this.OnFuelChanged();
                this.OnPropertyChanged("Fuel");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
        private int _Fuel;
        partial void OnFuelChanging(int value);
        partial void OnFuelChanged();
        /// <summary>
        /// There are no comments for Property Bull in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Bull")]
        public int Bull
        {
            get
            {
                return this._Bull;
            }
            set
            {
                this.OnBullChanging(value);
                this._Bull = value;
                this.OnBullChanged();
                this.OnPropertyChanged("Bull");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
        private int _Bull;
        partial void OnBullChanging(int value);
        partial void OnBullChanged();
        /// <summary>
        /// There are no comments for Property Firepower in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Firepower")]
        public int Firepower
        {
            get
            {
                return this._Firepower;
            }
            set
            {
                this.OnFirepowerChanging(value);
                this._Firepower = value;
                this.OnFirepowerChanged();
                this.OnPropertyChanged("Firepower");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
        private int _Firepower;
        partial void OnFirepowerChanging(int value);
        partial void OnFirepowerChanged();
        /// <summary>
        /// There are no comments for Property Torpedo in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Torpedo")]
        public int Torpedo
        {
            get
            {
                return this._Torpedo;
            }
            set
            {
                this.OnTorpedoChanging(value);
                this._Torpedo = value;
                this.OnTorpedoChanged();
                this.OnPropertyChanged("Torpedo");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
        private int _Torpedo;
        partial void OnTorpedoChanging(int value);
        partial void OnTorpedoChanged();
        /// <summary>
        /// There are no comments for Property AA in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("AA")]
        public int AA
        {
            get
            {
                return this._AA;
            }
            set
            {
                this.OnAAChanging(value);
                this._AA = value;
                this.OnAAChanged();
                this.OnPropertyChanged("AA");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
        private int _AA;
        partial void OnAAChanging(int value);
        partial void OnAAChanged();
        /// <summary>
        /// There are no comments for Property Armer in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Armer")]
        public int Armer
        {
            get
            {
                return this._Armer;
            }
            set
            {
                this.OnArmerChanging(value);
                this._Armer = value;
                this.OnArmerChanged();
                this.OnPropertyChanged("Armer");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
        private int _Armer;
        partial void OnArmerChanging(int value);
        partial void OnArmerChanged();
        /// <summary>
        /// There are no comments for Property Luck in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Luck")]
        public int Luck
        {
            get
            {
                return this._Luck;
            }
            set
            {
                this.OnLuckChanging(value);
                this._Luck = value;
                this.OnLuckChanged();
                this.OnPropertyChanged("Luck");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
        private int _Luck;
        partial void OnLuckChanging(int value);
        partial void OnLuckChanged();
        /// <summary>
        /// There are no comments for Property Admiral in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Admiral")]
        public global::HiyoshiCfhClient.HiyoshiCfhWeb.Models.Admiral Admiral
        {
            get
            {
                return this._Admiral;
            }
            set
            {
                this.OnAdmiralChanging(value);
                this._Admiral = value;
                this.OnAdmiralChanged();
                this.OnPropertyChanged("Admiral");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
        private global::HiyoshiCfhClient.HiyoshiCfhWeb.Models.Admiral _Admiral;
        partial void OnAdmiralChanging(global::HiyoshiCfhClient.HiyoshiCfhWeb.Models.Admiral value);
        partial void OnAdmiralChanged();
        /// <summary>
        /// There are no comments for Property ShipInfo in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ShipInfo")]
        public global::HiyoshiCfhClient.HiyoshiCfhWeb.Models.ShipInfo ShipInfo
        {
            get
            {
                return this._ShipInfo;
            }
            set
            {
                this.OnShipInfoChanging(value);
                this._ShipInfo = value;
                this.OnShipInfoChanged();
                this.OnPropertyChanged("ShipInfo");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
        private global::HiyoshiCfhClient.HiyoshiCfhWeb.Models.ShipInfo _ShipInfo;
        partial void OnShipInfoChanging(global::HiyoshiCfhClient.HiyoshiCfhWeb.Models.ShipInfo value);
        partial void OnShipInfoChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for ShipSpeed in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("ShipSpeed")]
    public enum ShipSpeed
    {
        [global::Microsoft.OData.Client.OriginalNameAttribute("Low")]
        Low = 10,
        [global::Microsoft.OData.Client.OriginalNameAttribute("Fast")]
        Fast = 20
    }
    /// <summary>
    /// Class containing all extension methods
    /// </summary>
    public static class ExtensionMethods
    {
        /// <summary>
        /// Get an entity of type global::HiyoshiCfhClient.HiyoshiCfhWeb.Models.ShipType as global::HiyoshiCfhClient.HiyoshiCfhWeb.Models.ShipTypeSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::HiyoshiCfhClient.HiyoshiCfhWeb.Models.ShipTypeSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::HiyoshiCfhClient.HiyoshiCfhWeb.Models.ShipType> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::HiyoshiCfhClient.HiyoshiCfhWeb.Models.ShipTypeSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::HiyoshiCfhClient.HiyoshiCfhWeb.Models.ShipType as global::HiyoshiCfhClient.HiyoshiCfhWeb.Models.ShipTypeSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="shipTypeId">The value of shipTypeId</param>
        public static global::HiyoshiCfhClient.HiyoshiCfhWeb.Models.ShipTypeSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::HiyoshiCfhClient.HiyoshiCfhWeb.Models.ShipType> source,
            int shipTypeId)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "ShipTypeId", shipTypeId }
            };
            return new global::HiyoshiCfhClient.HiyoshiCfhWeb.Models.ShipTypeSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::HiyoshiCfhClient.HiyoshiCfhWeb.Models.ShipInfo as global::HiyoshiCfhClient.HiyoshiCfhWeb.Models.ShipInfoSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::HiyoshiCfhClient.HiyoshiCfhWeb.Models.ShipInfoSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::HiyoshiCfhClient.HiyoshiCfhWeb.Models.ShipInfo> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::HiyoshiCfhClient.HiyoshiCfhWeb.Models.ShipInfoSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::HiyoshiCfhClient.HiyoshiCfhWeb.Models.ShipInfo as global::HiyoshiCfhClient.HiyoshiCfhWeb.Models.ShipInfoSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="shipInfoId">The value of shipInfoId</param>
        public static global::HiyoshiCfhClient.HiyoshiCfhWeb.Models.ShipInfoSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::HiyoshiCfhClient.HiyoshiCfhWeb.Models.ShipInfo> source,
            int shipInfoId)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "ShipInfoId", shipInfoId }
            };
            return new global::HiyoshiCfhClient.HiyoshiCfhWeb.Models.ShipInfoSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::HiyoshiCfhClient.HiyoshiCfhWeb.Models.Admiral as global::HiyoshiCfhClient.HiyoshiCfhWeb.Models.AdmiralSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::HiyoshiCfhClient.HiyoshiCfhWeb.Models.AdmiralSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::HiyoshiCfhClient.HiyoshiCfhWeb.Models.Admiral> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::HiyoshiCfhClient.HiyoshiCfhWeb.Models.AdmiralSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::HiyoshiCfhClient.HiyoshiCfhWeb.Models.Admiral as global::HiyoshiCfhClient.HiyoshiCfhWeb.Models.AdmiralSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="admiralId">The value of admiralId</param>
        public static global::HiyoshiCfhClient.HiyoshiCfhWeb.Models.AdmiralSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::HiyoshiCfhClient.HiyoshiCfhWeb.Models.Admiral> source,
            int admiralId)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "AdmiralId", admiralId }
            };
            return new global::HiyoshiCfhClient.HiyoshiCfhWeb.Models.AdmiralSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::HiyoshiCfhClient.HiyoshiCfhWeb.Models.Ship as global::HiyoshiCfhClient.HiyoshiCfhWeb.Models.ShipSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::HiyoshiCfhClient.HiyoshiCfhWeb.Models.ShipSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::HiyoshiCfhClient.HiyoshiCfhWeb.Models.Ship> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::HiyoshiCfhClient.HiyoshiCfhWeb.Models.ShipSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::HiyoshiCfhClient.HiyoshiCfhWeb.Models.Ship as global::HiyoshiCfhClient.HiyoshiCfhWeb.Models.ShipSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="shipUid">The value of shipUid</param>
        public static global::HiyoshiCfhClient.HiyoshiCfhWeb.Models.ShipSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::HiyoshiCfhClient.HiyoshiCfhWeb.Models.Ship> source,
            int shipUid)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "ShipUid", shipUid }
            };
            return new global::HiyoshiCfhClient.HiyoshiCfhWeb.Models.ShipSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
    }
}
namespace HiyoshiCfhClient.Default
{
    /// <summary>
    /// There are no comments for Container in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("Container")]
    public partial class Container : global::Microsoft.OData.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new Container object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
        public Container(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::Microsoft.OData.Client.ODataProtocolVersion.V4)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
            this.Format.UseJson();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "HiyoshiCfhWeb.Models", "HiyoshiCfhClient.HiyoshiCfhWeb.Models");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            resolvedType = this.DefaultResolveType(typeName, "Default", "HiyoshiCfhClient.Default");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            global::Microsoft.OData.Client.OriginalNameAttribute originalNameAttribute = (global::Microsoft.OData.Client.OriginalNameAttribute)global::System.Linq.Enumerable.SingleOrDefault(global::Microsoft.OData.Client.Utility.GetCustomAttributes(clientType, typeof(global::Microsoft.OData.Client.OriginalNameAttribute), true));
            if (clientType.Namespace.Equals("HiyoshiCfhClient.HiyoshiCfhWeb.Models", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("HiyoshiCfhWeb.Models.", originalNameAttribute.OriginalName);
                }
                return string.Concat("HiyoshiCfhWeb.Models.", clientType.Name);
            }
            if (clientType.Namespace.Equals("HiyoshiCfhClient.Default", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("Default.", originalNameAttribute.OriginalName);
                }
                return string.Concat("Default.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for ShipTypes in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ShipTypes")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::HiyoshiCfhClient.HiyoshiCfhWeb.Models.ShipType> ShipTypes
        {
            get
            {
                if ((this._ShipTypes == null))
                {
                    this._ShipTypes = base.CreateQuery<global::HiyoshiCfhClient.HiyoshiCfhWeb.Models.ShipType>("ShipTypes");
                }
                return this._ShipTypes;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::HiyoshiCfhClient.HiyoshiCfhWeb.Models.ShipType> _ShipTypes;
        /// <summary>
        /// There are no comments for ShipInfoes in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ShipInfoes")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::HiyoshiCfhClient.HiyoshiCfhWeb.Models.ShipInfo> ShipInfoes
        {
            get
            {
                if ((this._ShipInfoes == null))
                {
                    this._ShipInfoes = base.CreateQuery<global::HiyoshiCfhClient.HiyoshiCfhWeb.Models.ShipInfo>("ShipInfoes");
                }
                return this._ShipInfoes;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::HiyoshiCfhClient.HiyoshiCfhWeb.Models.ShipInfo> _ShipInfoes;
        /// <summary>
        /// There are no comments for Admirals in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Admirals")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::HiyoshiCfhClient.HiyoshiCfhWeb.Models.Admiral> Admirals
        {
            get
            {
                if ((this._Admirals == null))
                {
                    this._Admirals = base.CreateQuery<global::HiyoshiCfhClient.HiyoshiCfhWeb.Models.Admiral>("Admirals");
                }
                return this._Admirals;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::HiyoshiCfhClient.HiyoshiCfhWeb.Models.Admiral> _Admirals;
        /// <summary>
        /// There are no comments for Ships in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Ships")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::HiyoshiCfhClient.HiyoshiCfhWeb.Models.Ship> Ships
        {
            get
            {
                if ((this._Ships == null))
                {
                    this._Ships = base.CreateQuery<global::HiyoshiCfhClient.HiyoshiCfhWeb.Models.Ship>("Ships");
                }
                return this._Ships;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::HiyoshiCfhClient.HiyoshiCfhWeb.Models.Ship> _Ships;
        /// <summary>
        /// There are no comments for ShipTypes in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
        public void AddToShipTypes(global::HiyoshiCfhClient.HiyoshiCfhWeb.Models.ShipType shipType)
        {
            base.AddObject("ShipTypes", shipType);
        }
        /// <summary>
        /// There are no comments for ShipInfoes in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
        public void AddToShipInfoes(global::HiyoshiCfhClient.HiyoshiCfhWeb.Models.ShipInfo shipInfo)
        {
            base.AddObject("ShipInfoes", shipInfo);
        }
        /// <summary>
        /// There are no comments for Admirals in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
        public void AddToAdmirals(global::HiyoshiCfhClient.HiyoshiCfhWeb.Models.Admiral admiral)
        {
            base.AddObject("Admirals", admiral);
        }
        /// <summary>
        /// There are no comments for Ships in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
        public void AddToShips(global::HiyoshiCfhClient.HiyoshiCfhWeb.Models.Ship ship)
        {
            base.AddObject("Ships", ship);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
            private static global::Microsoft.OData.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
            private const string Edmx = @"<edmx:Edmx Version=""4.0"" xmlns:edmx=""http://docs.oasis-open.org/odata/ns/edmx"">
  <edmx:DataServices>
    <Schema Namespace=""HiyoshiCfhWeb.Models"" xmlns=""http://docs.oasis-open.org/odata/ns/edm"">
      <EntityType Name=""ShipType"">
        <Key>
          <PropertyRef Name=""ShipTypeId"" />
        </Key>
        <Property Name=""ShipTypeId"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""Name"" Type=""Edm.String"" />
        <Property Name=""SortNumber"" Type=""Edm.Int32"" Nullable=""false"" />
      </EntityType>
      <EntityType Name=""ShipInfo"">
        <Key>
          <PropertyRef Name=""ShipInfoId"" />
        </Key>
        <Property Name=""ShipInfoId"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""SortId"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""Name"" Type=""Edm.String"" />
        <Property Name=""ShipTypeId"" Type=""Edm.Int32"" />
        <Property Name=""ShipSpeed"" Type=""HiyoshiCfhWeb.Models.ShipSpeed"" Nullable=""false"" />
        <Property Name=""NextRemodelingLevel"" Type=""Edm.Int32"" />
        <NavigationProperty Name=""ShipType"" Type=""HiyoshiCfhWeb.Models.ShipType"">
          <ReferentialConstraint Property=""ShipTypeId"" ReferencedProperty=""ShipTypeId"" />
        </NavigationProperty>
      </EntityType>
      <EntityType Name=""Admiral"">
        <Key>
          <PropertyRef Name=""AdmiralId"" />
        </Key>
        <Property Name=""AdmiralId"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""MemberId"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""Name"" Type=""Edm.String"" />
        <Property Name=""Experience"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""Level"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""MaxShipCount"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""Rank"" Type=""Edm.String"" />
        <NavigationProperty Name=""Ships"" Type=""Collection(HiyoshiCfhWeb.Models.Ship)"" />
      </EntityType>
      <EntityType Name=""Ship"">
        <Key>
          <PropertyRef Name=""ShipUid"" />
        </Key>
        <Property Name=""ShipUid"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""AdmiralId"" Type=""Edm.Int32"" />
        <Property Name=""ShipId"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""ShipInfoId"" Type=""Edm.Int32"" />
        <Property Name=""Level"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""IsLocked"" Type=""Edm.Boolean"" Nullable=""false"" />
        <Property Name=""Exp"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""ExpForNextLevel"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""Hp"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""Fuel"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""Bull"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""Firepower"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""Torpedo"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""AA"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""Armer"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""Luck"" Type=""Edm.Int32"" Nullable=""false"" />
        <NavigationProperty Name=""Admiral"" Type=""HiyoshiCfhWeb.Models.Admiral"">
          <ReferentialConstraint Property=""AdmiralId"" ReferencedProperty=""AdmiralId"" />
        </NavigationProperty>
        <NavigationProperty Name=""ShipInfo"" Type=""HiyoshiCfhWeb.Models.ShipInfo"">
          <ReferentialConstraint Property=""ShipInfoId"" ReferencedProperty=""ShipInfoId"" />
        </NavigationProperty>
      </EntityType>
      <EnumType Name=""ShipSpeed"">
        <Member Name=""Low"" Value=""10"" />
        <Member Name=""Fast"" Value=""20"" />
      </EnumType>
    </Schema>
    <Schema Namespace=""Default"" xmlns=""http://docs.oasis-open.org/odata/ns/edm"">
      <EntityContainer Name=""Container"">
        <EntitySet Name=""ShipTypes"" EntityType=""HiyoshiCfhWeb.Models.ShipType"" />
        <EntitySet Name=""ShipInfoes"" EntityType=""HiyoshiCfhWeb.Models.ShipInfo"">
          <NavigationPropertyBinding Path=""ShipType"" Target=""ShipTypes"" />
        </EntitySet>
        <EntitySet Name=""Admirals"" EntityType=""HiyoshiCfhWeb.Models.Admiral"">
          <NavigationPropertyBinding Path=""Ships"" Target=""Ships"" />
        </EntitySet>
        <EntitySet Name=""Ships"" EntityType=""HiyoshiCfhWeb.Models.Ship"">
          <NavigationPropertyBinding Path=""Admiral"" Target=""Admirals"" />
          <NavigationPropertyBinding Path=""ShipInfo"" Target=""ShipInfoes"" />
        </EntitySet>
      </EntityContainer>
    </Schema>
  </edmx:DataServices>
</edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
            public static global::Microsoft.OData.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
            private static global::Microsoft.OData.Edm.IEdmModel LoadModelFromString()
            {
                global::System.Xml.XmlReader reader = CreateXmlReader(Edmx);
                try
                {
                    return global::Microsoft.OData.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.3.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
}
